'use client';
import {useParams} from 'next/navigation';
import {Shell,Card,Stat} from '@/components/page';
import {useEffect,useMemo,useState} from 'react';

type State={profile:any;currency:any;modules:any[];energy:any;explorers:any[];missions:any[];crafts:any[]};
const names:Record<string,string>={base:'Base Hub',explore:'Exploration',workshop:'Workshop',explorers:'Explorers',inventory:'Inventory',market:'Market',guilds:'Guilds',seasons:'Seasons',leaderboard:'Leaderboard',prestige:'Void Ascension',profile:'Profile',admin:'Admin Control'};
const zoneFallback=[['T1','Dark Edge',.1,10,180,10,.2],['T2','Crystal Grove',.25,18,360,22,.6],['T3','Silica Desert',.4,28,720,45,1.5],['T4','Ion Rift',.6,40,1500,90,3.5],['T5','Void Core',.8,55,2700,170,8],['RAID','Group Assault',.9,80,3600,400,20]];
const modules=[['energy','Energy Generator',100,'+20 energy cap / level','+1 regen / hour'],['workshop','Workshop',120,'+8% craft speed / level','New recipe tier every 5 levels'],['storage','Storage',110,'×1.3 resource cap / level','Protects resource overflow'],['lab','Lab',140,'+4% explorer stats / level','2 slots L5 · 3 L10 · 4 L15']];
const fmt=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n||0);
export default function Section(){
 const {section}=useParams<{section:string}>(); const title=names[section]??'VOIDRUN';
 const [state,setState]=useState<State|null>(null); const [zones,setZones]=useState<any[]>([]); const [recipes,setRecipes]=useState<any[]>([]); const [market,setMarket]=useState<any[]>([]); const [catalog,setCatalog]=useState<any[]>([]); const [busy,setBusy]=useState(''); const [msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/state',{cache:'no-store'});if(r.ok)setState(await r.json());if(section==='explore'){const z=await fetch('/api/zones');if(z.ok)setZones(await z.json())}if(section==='workshop'){const x=await fetch('/api/recipes');if(x.ok)setRecipes(await x.json())}if(section==='market'){const x=await fetch('/api/market/listings');if(x.ok)setMarket(await x.json())}if(section==='explorers'){const x=await fetch('/api/explorers/catalog');if(x.ok)setCatalog(await x.json())}}
 useEffect(()=>{load().catch(()=>setMsg('Unable to load station state.'))},[section]);
 async function act(path:string,body?:unknown){setBusy(path);setMsg('');try{const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'COMMAND_FAILED');setMsg('Command accepted.');await load();return d}catch(e){setMsg(e instanceof Error?e.message:'Command failed.')}finally{setBusy('')}}
 const first=state?.explorers?.[0]; const energy=state?.energy?.current??0; const cap=state?.energy?.cap??100;
 if(section==='base')return <Shell title={title} eyebrow="HOME // STATION"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Credit" value={fmt(state?.currency?.credit)} sub="soft currency"/><Stat label="Void Shard" value={fmt(state?.currency?.shard)} sub="off-chain utility ledger"/><Stat label="Energy" value={`${energy} / ${cap}`} sub="time regeneration only"/><Stat label="Reputation" value={state?.profile?.reputation??0}/></div><div className="mt-6 grid grid-auto gap-4">{modules.map(([id,n,c,e1,e2])=>{const m=state?.modules?.find(x=>x.type===id);const l=m?.level??1;return <Card key={id}><div className="flex items-start justify-between"><div><div className="text-lg font-bold">{n}</div><div className="mt-1 text-xs uppercase tracking-wider text-cyan-300">Level {l}</div></div><div className="text-xs text-slate-500">Upgrade</div></div><p className="mt-5 text-sm text-slate-400">{e1}</p><p className="mt-1 text-xs text-slate-500">{e2}</p><button disabled={!!busy} onClick={()=>act('base/upgrade',{type:id})} className="mt-5 w-full rounded-xl border border-cyan-300/20 px-4 py-3 text-sm text-cyan-200">Upgrade • {c} Credit</button></Card>})}</div>{msg&&<Notice text={msg}/>}</Shell>;
 if(section==='explore')return <Shell title={title} eyebrow="FIELD // ZONES"><div className="mb-5 rounded-xl border border-cyan-300/10 bg-cyan-300/[.03] p-4 text-sm text-slate-400">Missions are server-resolved. Decision clues modify effective hazard or yield; the client never chooses the reward.</div><div className="grid grid-auto gap-4">{(zones.length?zones:zoneFallback).map((z:any,i:number)=>{const [id,name,h,e,d,c,s]=Array.isArray(z)?z:[`T${i+1}`,z.name,z.hazard,z.energy_cost,z.duration,z.credit_yield,z.shard_yield];const locked=(id==='T4'&&((state?.profile?.reputation??0)<3))||(id==='T5'&&((state?.profile?.reputation??0)<5));return <Card key={id}><div className="flex justify-between"><div><div className="text-xs text-cyan-300">{id}</div><h2 className="mt-1 text-xl font-bold">{name}</h2></div><div className="text-xs text-slate-500">Hazard {Number(h).toFixed(2)}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><div><span className="text-slate-500">Energy</span><br/>{e}</div><div><span className="text-slate-500">Duration</span><br/>{Math.round(Number(d)/60)} min</div><div><span className="text-slate-500">Yield</span><br/>{c} C · {s} S</div></div><button disabled={locked||!!busy||!first} onClick={()=>act('missions/start',{zoneId:i+1,explorerId:first?.id})} className="mt-5 w-full rounded-xl bg-white/5 px-4 py-3 text-sm">{locked?'Requires Reputation':!first?'No explorer':'Deploy explorer'}</button></Card>})}</div>{msg&&<Notice text={msg}/>}</Shell>;
 if(section==='workshop')return <Shell title={title} eyebrow="FABRICATION // WORKSHOP"><div className="mb-5 flex flex-wrap gap-3"><Stat label="Workshop" value={`L${state?.modules?.find(x=>x.type==='workshop')?.level??1}`} sub="8% speed per level"/><Stat label="Active queue" value={state?.crafts?.filter(x=>x.status==='active').length??0}/></div><div className="grid grid-auto gap-4">{recipes.slice(0,20).map(r=><Card key={r.id}><div className="text-lg font-bold">{r.name}</div><div className="mt-2 text-xs text-slate-500">{r.time_minutes} min base · {fmt(r.credit_cost)} Credit</div><pre className="mt-4 overflow-auto rounded-lg bg-black/20 p-3 text-xs text-slate-400">{JSON.stringify(r.materials,null,2)}</pre><button disabled={!!busy} onClick={()=>act('craft/start',{recipeId:r.id})} className="mt-4 w-full rounded-xl border border-white/10 px-4 py-3">Craft</button></Card>)}</div>{msg&&<Notice text={msg}/>}</Shell>;
 if(section==='explorers')return <Shell title={title} eyebrow="ROSTER // EXPLORERS"><div className="grid grid-auto gap-4">{(state?.explorers?.length?state.explorers:catalog.slice(0,12)).map((e:any)=><Card key={e.id??e.name}><div className="flex justify-between"><div><div className="text-xs text-cyan-300">{e.rarity}</div><div className="mt-1 text-xl font-bold">{e.name??'Explorer'}</div></div><div className="text-xs text-slate-500">Level {e.level??1}</div></div><div className="mt-5 grid grid-cols-4 gap-2 text-center text-xs">{Object.entries(e.stats||{}).map(([k,v])=><div key={k} className="rounded-lg bg-white/[.03] p-2"><div className="text-slate-500">{k}</div><div className="mt-1 font-bold">{String(v)}</div></div>)}</div>{e.id&&<div className="mt-4 grid grid-cols-2 gap-2"><button disabled={!!busy} onClick={()=>act('explorers/levelup',{explorerId:e.id})} className="rounded-xl border border-cyan-300/20 px-3 py-3 text-sm">Level up</button><button disabled={!!busy} onClick={()=>act('explorers/ascend',{explorerId:e.id})} className="rounded-xl border border-fuchsia-300/20 px-3 py-3 text-sm">Ascend</button></div>}</Card>)}</div>{msg&&<Notice text={msg}/>}</Shell>;
 if(section==='inventory')return <Shell title={title} eyebrow="STORAGE // INVENTORY"><div className="grid grid-auto gap-4">{['Gear','Consumables','Materials','Blueprints','Cosmetics'].map((cat)=><Card key={cat}><div className="text-lg font-bold">{cat}</div><p className="mt-2 text-sm text-slate-500">Server inventory category. Items, ownership and durability are authoritative in Supabase.</p><div className="mt-5 text-sm text-slate-400">{state?.missions?.length??0} recent mission records · {state?.crafts?.length??0} craft records</div></Card>)}</div></Shell>;
 if(section==='market')return <Shell title={title} eyebrow="EXCHANGE // P2P MARKET"><div className="mb-5 grid grid-cols-2 gap-3"><Stat label="Listing fee" value="2 C"/><Stat label="Trade tax" value="5%" sub="2% burn · 2% treasury · 1% rewards"/></div><div className="grid grid-auto gap-4">{market.length?market.map(x=><Card key={x.id}><div className="flex justify-between"><div><div className="text-xs text-slate-500">{x.items?.rarity??'Item'}</div><div className="font-bold">{x.items?.subtype??x.items?.type??'Unknown item'}</div></div><div className="text-lg font-bold">{fmt(x.price)} C</div></div><button disabled={!!busy} onClick={()=>act('market/buy',{listingId:x.id})} className="mt-5 w-full rounded-xl bg-cyan-300 px-4 py-3 font-bold text-slate-950">Buy</button></Card>):<Empty text="No active listings."/>}</div>{msg&&<Notice text={msg}/>}</Shell>;
 if(section==='guilds')return <Shell title={title} eyebrow="SOCIAL // GUILDS"><Card><div className="text-xl font-bold">Build a crew</div><p className="mt-2 text-sm text-slate-400">Guild halls, contribution-weighted raids and reputation progression are server-authoritative.</p><button disabled={!!busy} onClick={()=>act('guild/create',{name:'Void Runners'})} className="mt-5 rounded-xl border border-cyan-300/20 px-5 py-3">Create Guild</button></Card><div className="mt-5 grid grid-auto gap-4"><Card><div className="font-bold">Group Assault</div><p className="mt-2 text-sm text-slate-500">Raid requires 2–4 players. Reward share follows contribution, role and performance.</p></Card><Card><div className="font-bold">Invite system</div><p className="mt-2 text-sm text-slate-500">Maximum 5 invites/week with diminishing rewards. Qualification occurs at Reputation 3.</p></Card></div>{msg&&<Notice text={msg}/>}</Shell>;
 if(section==='seasons')return <Shell title={title} eyebrow="SEASON // 08 WEEKS"><div className="grid grid-auto gap-4"><Card><div className="text-xs text-cyan-300">FREE TRACK</div><div className="mt-2 text-2xl font-bold">Season 1 — Awakening</div><p className="mt-3 text-sm text-slate-400">56-day cadence. Rewards focus on cosmetics and consumables.</p></Card><Card><div className="text-xs text-fuchsia-300">PREMIUM TRACK</div><div className="mt-2 text-2xl font-bold">150 Void Shards</div><p className="mt-3 text-sm text-slate-400">No guaranteed financial return. Premium rewards are game items.</p></Card></div></Shell>;
 if(section==='leaderboard')return <Shell title={title} eyebrow="RANKING // TOP 100"><Card><div className="space-y-3">{Array.from({length:10}).map((_,i)=><div key={i} className="flex items-center justify-between rounded-xl bg-white/[.03] p-3"><span className="text-cyan-300">#{i+1}</span><span>Runner {String(i+1).padStart(2,'0')}</span><span className="text-slate-400">{10000-i*371} XP</span></div>)}</div></Card></Shell>;
 if(section==='prestige')return <Shell title={title} eyebrow="RESET // ASCENSION"><Card className="border-fuchsia-300/20"><div className="text-xs uppercase tracking-wider text-fuchsia-300">Requirement</div><div className="mt-2 text-3xl font-black">All modules ≥ L15</div><p className="mt-4 text-sm text-slate-400">Resets module levels and Credit. Keeps explorers, items, cosmetics and Shard ledger. Grants +5% yield per Void Mark, capped at +50%.</p><button disabled={!!busy} onClick={()=>act('prestige')} className="mt-6 w-full rounded-xl border border-fuchsia-300/30 px-4 py-3">Attempt Void Ascension</button></Card>{msg&&<Notice text={msg}/>}</Shell>;
 if(section==='profile')return <Shell title={title} eyebrow="IDENTITY // SETTINGS"><div className="grid grid-auto gap-4"><Card><div className="text-xs text-slate-500">Account</div><div className="mt-2 break-all text-sm">{state?.profile?.email??'Guest account'}</div></Card><Card><div className="font-bold">Wallet</div><p className="mt-2 text-sm text-slate-500">Phase 4 only. Wallet is disabled by default and never required to play.</p></Card><Card><div className="font-bold">Danger zone</div><p className="mt-2 text-sm text-red-300/70">Guest reset is intentionally destructive and must be explicitly implemented server-side.</p></Card></div></Shell>;
 if(section==='admin')return <Shell title={title} eyebrow="CONTROL // ADMIN"><Card><div className="text-xl font-bold">Economy control</div><p className="mt-2 text-sm text-slate-400">Balance values are database-driven. Admin routes require the configured server-side admin email.</p><button onClick={()=>act('admin/economy')} className="mt-5 rounded-xl border border-cyan-300/20 px-5 py-3">Refresh economy metrics</button></Card>{msg&&<Notice text={msg}/>}</Shell>;
 return <Shell title={title}><Card><div className="text-xl font-bold">VOIDRUN</div><p className="mt-2 text-slate-400">Choose a station module from the navigation.</p></Card></Shell>;
}
function Notice({text}:{text:string}){return <div className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-300/[.03] p-4 text-sm text-emerald-300">{text}</div>}
function Empty({text}:{text:string}){return <Card><div className="py-10 text-center text-sm text-slate-500">{text}</div></Card>}
